In [2]:
import numpy as np

### Try it yourself

Check the type of the array and Value type for the given array **c**


In [3]:
c = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

# Enter your code here
print(c.dtype)
print(type(c))

float64
<class 'numpy.ndarray'>


### Try it yourself

Assign the value 20 for the second element in the given array.


In [4]:
a = np.array([10, 2, 30, 40,50])

# Enter your code here
a[1] = 20
a

array([10, 20, 30, 40, 50])

### Try it yourself

Print the even elements in the given array.


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Enter your code here
# for i in range(len(arr)):
#     if arr[i] % 2 == 0:
#         print(arr[i])
arr[1::2]

array([2, 4, 6, 8])

### Try it yourself

Find the sum of maximum and minimum value in the given numpy array


<hr>


In [6]:
c = np.array([-10, 201, 43, 94, 502])

# Enter your code here
ans = c.max() + c.min()
print(ans)

492


### Try it yourself

Perform addition operation on the given numpy array arr1 and arr2:


In [13]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Enter your code here
arr3 =  arr1 + arr2
arr3

array([30, 32, 34, 36, 38, 40])

### Try it yourself

Perform subtraction operation on the given numpy array arr1 and arr2:


In [11]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Enter your code here
arr3 =np.subtract(arr1,arr2)
arr3

array([-10,  -1,   8,  17,  26,  35])

### Try it yourself

Perform multiply operation on the given numpy array arr1 and arr2:


In [10]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])

# Enter your code here
arr4 = np.multiply(arr1, arr2)
arr4

array([ 20,  20,  60, 120, 200, 300])

### Try it yourself

Perform division operation on the given numpy array arr1 and arr2:


In [14]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

# Enter your code here
arr3 = np.divide(arr1, arr2)
arr3

array([ 3.33333333,  4.        ,  3.        ,  5.        , 25.        ,
        1.81818182])

### Try it yourself

Perform dot operation on the given numpy array ar1 and ar2:


In [15]:
arr1 = np.array([3, 5])
arr2 = np.array([2, 4])

# Enter your code here
arr3 = arr1.dot(arr2)
arr3

np.int64(26)

### Try it yourself

Add Constant 5 to the given numpy array ar:


In [24]:
arr = np.array([1, 2, 3, -1]) 

# Enter your code here
arr = np.append(arr, [5])
arr

array([ 1,  2,  3, -1,  5])

## Quiz on 1D Numpy Array


Implement the following vector subtraction in numpy: u-v


In [28]:
# Write your code below and press Shift+Enter to execute

u = np.array([1, 0])
v = np.array([0, 1])

c = np.subtract(u, v)
c

array([ 1, -1])

<details><summary>Click here for the solution</summary>

```python
u - v
```

</details>


<hr>


Multiply the numpy array z with -2:


In [29]:
# Write your code below and press Shift+Enter to execute

z = np.array([2, 4])
z *= (-2)
z

array([-4, -8])

<details><summary>Click here for the solution</summary>

```python
-2 * z
```

</details>


<hr>


Consider the list <code>\[1, 2, 3, 4, 5]</code> and <code>\[1, 0, 1, 0, 1]</code>. Cast both lists to a numpy array then multiply them together:


In [31]:
# Write your code below and press Shift+Enter to execute
a = [1,2,3,4,5]
b = [1,0,1,0,1]
c = np.array(a)
d = np.array(b)
e = np.multiply(c, d)
e

array([1, 0, 3, 0, 5])

<details><summary>Click here for the solution</summary>

```python
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])
a * b
```

</details>


<hr>


Convert the list <code>\[1, 2, 3]</code> and <code>\[8, 9, 10]</code> to numpy arrays <code>arr1</code> and <code>arr2</code>. Then perform <code>Addition</code> , <code>Subtraction</code> , <code>Multiplication</code> , <code>Division</code> and <code>Dot Operation</code> on the <code>arr1</code> and <code>arr2</code>.



In [34]:
# Write your code below and press Shift+Enter to execute
a= [1 ,2 ,3]
b = [8, 9 , 10]
arr1 = np.array(a)
arr2 = np.array(b)
sum_arrays = arr1 + arr2
sub = np.subtract(arr1, arr2)
multi = np.multiply(arr1, arr2)
div = np.divide(arr1,arr2)
dot_arrays = np.dot(arr1,arr2)
print(sum_arrays,'\n', sub, '\n', multi, '\n', div, '\n', dot_arrays)

[ 9 11 13] 
 [-7 -7 -7] 
 [ 8 18 30] 
 [0.125      0.22222222 0.3       ] 
 56


<details><summary>Click here for the solution</summary>

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])

arr3 = np.add(arr1, arr2)
arr3

arr4 = np.subtract(arr1, arr2)
arr4

arr5 = np.multiply(arr1, arr2)
arr5


arr6 = np.divide(arr1, arr2)
arr6

arr7 = np.dot(arr1, arr2)
arr7
```

</details>


Convert the list <code>\[1, 2, 3, 4, 5]</code> and <code>\[6, 7, 8, 9, 10]</code> to numpy arrays <code>arr1</code> and <code>arr2</code>. Then find the even and odd numbers from <code>arr1</code> and <code>arr2</code>.


In [39]:
# Write your code below and press Shift+Enter to execute
a = [1,2,3,4,5]
b = [6,7,8,9,10]

arr1 = np.array(a)
arr2 = np.array(b)
arr3 = np.concatenate((arr1, arr2))

print('even')
print(arr3[1::2])
print('odd')
print(arr3[0::2])

even
[ 2  4  6  8 10]
odd
[1 3 5 7 9]


<details><summary>Click here for the solution</summary>

```python


arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

#Starting index in slice is 1 as first even element(2) in array1 is at index 1
even_arr1 = arr1[1:5:2]
print("even for array1",even_arr1)
    
#Starting index in slice is 0 as first odd element(1) in array1 is at index 0
odd_arr1=arr1[0:5:2]
print("odd for array1",odd_arr1)

#Starting index in slice is 0 as first even element(6) in array2 is at index 0
even_arr2 = arr2[0:5:2]
print("even for array2",even_arr2)
    
    
#Starting index in slice is 1 as first odd element(7) in array2 is at index 1
odd_arr2=arr2[1:5:2]
print("odd for array2",odd_arr2)

```

</details>


<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. 
<hr>


<h2>Quiz on 2D Numpy Array</h2>


Consider the following list <code>a</code>, convert it to Numpy Array. 


In [40]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr = np.array(a)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<details><summary>Click here for the solution</summary>

```python
A = np.array(a)
A
```

</details>


Calculate the numpy array size.


In [44]:
# Write your code below and press Shift+Enter to execute
arr.size

12

<details><summary>Click here for the solution</summary>

```python
A.size
```

</details>


Access the element on the first row and first and second columns.


In [50]:
# Write your code below and press Shift+Enter to execute
arr[0,:2]

array([1, 2])

<details><summary>Click here for the solution</summary>

```python
A[0][0:2]
```

</details>


Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [54]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
ans = np.dot(arr, B)
ans

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

<details><summary>Click here for the solution</summary>

```python
X = np.dot(A,B)
X
```

</details>


<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. 
<hr>
